PROJECT=Mathematics_And_Statistics

GENERATED_EXECUTABLES=bin/$(LC_PROJECT)-demo \
                      bin/fractions \
                      bin/mean_and_variance \
                      bin/number_of_combinations

GENERATED_SOURCES=$(PROJECT_ROOT_SOURCE) \
                  $(HG_STATE_SOURCE) \
                  $(PROJECT_DEMO_SOURCE)

SCRIPTS=

TEST_OUTPUT=tests/results

